require File.expand_path(File.dirname(__FILE__) + "/commands/base_command")
require File.expand_path(File.dirname(__FILE__) + "/commands/help")
require File.expand_path(File.dirname(__FILE__) + "/commands/version")
require File.expand_path(File.dirname(__FILE__) + "/commands/run")
require File.expand_path(File.dirname(__FILE__) + "/commands/list")
require File.expand_path(File.dirname(__FILE__) + "/commands/slave_start")
require File.expand_path(File.dirname(__FILE__) + "/commands/slave_stop")
require File.expand_path(File.dirname(__FILE__) + "/commands/slave_run")