require "testjour/commands/help"
require "testjour/commands/version"
require "testjour/commands/run"
require "testjour/commands/list"
require "testjour/commands/slave_start"
require "testjour/commands/slave_stop"
require "testjour/commands/slave_run"