require "testjour/commands/help"
require "testjour/commands/version"
require "testjour/commands/run"
require "testjour/commands/run_slave"
require "testjour/commands/run_remote"
require "testjour/commands/load_schema"
require "testjour/commands/mysql_create"
require "testjour/commands/mysql_drop"